# Generated by Django 5.2.1 on 2025-07-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('thumbnail', models.ImageField(upload_to='project_thumbnails/', verbose_name='Miniatura')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Curtidas')),
                ('access_link', models.URLField(verbose_name='Link de Acesso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-created_at'],
            },
        ),
    ]
